### ISSUE TITLE
Add Task Dashboard

### ISSUE THREAD

**Issue by daebert** [lmachens/tasks#7] opened 2021-04-21 13:13 UTC
![image](https://user-images.githubusercontent.com/81586917/115559546-141a1a00-a2b4-11eb-812c-88b2ceaf5b82.png)

## HTML
- button
- Title (h2)
- input type checkbox
- input type radio

**Comment by lmachens** [comment] 2021-04-29 11:46
Duplicate of #6

**Closed as completed by lmachens** 2021-04-29 11:46 UTC
